-- CREATE TABLE plants (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   name TEXT,
--   family TEXT,
--   image TEXT
-- );

-- INSERT INTO plants (name, family) VALUES ('Deliciosa', 'Monstera');
-- INSERT INTO plants (name, family) VALUES ('Variegata', 'Monstera');
-- INSERT INTO plants (name, family) VALUES ('Adansonii', 'Monstera');
-- INSERT INTO plants (name, family) VALUES ('Rhaphidophora Tetrasperma', 'Monstera');
